services:
  barber_db_postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: viepovsky
      POSTGRES_PASSWORD: password
      POSTGRES_DB: barber
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5430:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: viepovsky@viepovsky.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    depends_on:
      - barber_db_postgres
    restart: unless-stopped

  recommendation_db_mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recommendation
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3300:3306
    networks:
      - mysql
    restart: unless-stopped

  mysql_workbench:
    container_name: mysql_workbench
    image: linuxserver/mysql-workbench
    environment:
      CUSTOM_USER: admin
      PASSWORD: admin
    volumes:
      - workbench:/var/lib/workbench
    ports:
      - 3000:3000
    networks:
      - mysql
    depends_on:
      - recommendation_db_mysql
    restart: unless-stopped

  notification_db_mongodb:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: viepovsky
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: notification
    volumes:
      - mongo:/var/lib/mongo
    ports:
      - 27017:27017
    networks:
      - mongodb
    restart: unless-stopped

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=viepovsky
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    volumes:
      - express:/var/lib/express
    ports:
      - 8000:8081
    networks:
      - mongodb
    depends_on:
      - notification_db_mongodb
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - microservices

  rabbitmq:
    image: rabbitmq:3.12.9-management-alpine
    container_name: rabbitmq
    networks:
      - microservices
    ports:
      - 5672:5672 #queues
      - 15672:15672 #management

#  spring-cloud-gateway:
#    container_name: gateway
#    image: viepovsky/spring-cloud-gateway:1.0-SNAPSHOT
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - 8083:8083
#    networks:
#      - microservices
#    depends_on:
#      - zipkin
#      - eureka-server

#  barber:
#    container_name: barber
#    image: viepovsky/barber:1.0-SNAPSHOT
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - 8080:8080
#    networks:
#      - microservices
#      - postgres
#    depends_on:
#      - zipkin
#      - eureka-server
#      - barber_db_postgres
#      - rabbitmq
#
#  recommendation:
#    container_name: recommendation
#    image: viepovsky/recommendation:1.0-SNAPSHOT
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - 8081:8081
#    networks:
#      - microservices
#      - mysql
#    depends_on:
#      - zipkin
#      - eureka-server
#      - recommendation_db_mysql
#      - rabbitmq
#
#  notification:
#    container_name: notification
#    image: viepovsky/notification:1.0-SNAPSHOT
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - 8082:8082
#    networks:
#      - microservices
#      - mongodb
#    depends_on:
#      - zipkin
#      - eureka-server
#      - notification_db_mongodb
#      - rabbitmq

networks:
  postgres:
  mysql:
  mongodb:
  microservices:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mysql:
  workbench:
  mongo:
  express:
